Add q4 roadmap
meilisearch/integration-guides pull request #143
Opened 2021-10-04 16:53 UTC by curquiza

2021-10-04 16:55 UTC, curquiza commented
FYI @alallema and @bidoubiwa!

Nothing should be surprising for you, but we will talk about it next Thursday in any case 🙂

2021-10-05 12:19 UTC, curquiza commented on roadmap/2021.md
> +- [ ] JavaScript SDK: add cache
```suggestion
- [X] Instant MeiliSearch: add cache
```

2021-10-05 12:33 UTC, tpayet approved these changes
lgtm 🎉 Let's go 🏄🏽‍♀️

2021-10-06 14:04 UTC, qdequele requested changes
I see that you deprioritize the SQL connector over WordPress. Will the WordPress integration use the PHP library or will it use a direct connection to the SQL database? Or will it go through the PHP SDK implementation in a special package? Do you know technically how a SQL connector would work?

2021-10-11 13:58 UTC, merged