Add dependency list
meilisearch/integration-guides pull request #159
Opened 2021-12-14 17:38 UTC by curquiza

Also, update the release guide.

2021-12-15 09:24 UTC, alallema reviewed
I like this new guide!

2021-12-15 09:24 UTC, alallema commented on resources/integration-release.md
> +For some integrations, we need to release a beta version of the integration before releasing the official one. For instance, during the MeiliSearch pre-release, we often need to release a beta versio
```suggestion
For some integrations, we need to release a beta version of the integration before releasing the official one. For instance, during the MeiliSearch pre-release, we often need to release a beta version of [meilisearch-js](https://github.com/meilisearch/meilisearch-js) to make the [mini-dashboard](https://github.com/meilisearch/mini-dashboard)) work with the future release of MeiliSearch.
```

2021-12-15 11:03 UTC, bidoubiwa requested changes

2021-12-15 11:03 UTC, bidoubiwa commented on resources/dependencies.md
> +
```suggestion

## Vuepress plugin

No dependencies for [vuepress-plugin-meilisearch]((https://github.com/meilisearch/vuepress-plugin-meilisearch/)

⚠️ Also, even if they are not parts of the integration team, we should keep in mind the following projects strongly depend on `vuepress-plugin-meilisearch`:

- The [documentation](https://docs.meilisearch.com/)

## Docs scraper

No dependencies for [docs-scraper](https://github.com/meilisearch/docs-scraper/).

⚠️ Also, even if they are not parts of the integration team, we should keep in mind the following projects strongly depend on `docs-scraper`:

- The [documentation](https://docs.meilisearch.com/)

```

2021-12-15 11:30 UTC, alallema approved these changes
LGTM! 🍣

2021-12-15 15:18 UTC, curquiza commented on resources/dependencies.md
> +
Yes, but not the scope of the integration team

2021-12-15 15:20 UTC, curquiza commented on resources/dependencies.md
> +They depend on [`meilisearch-js`](https://github.com/meilisearch/meilisearch-js):
They are not the dependencies of the JS SDK. They have the JS SDK as a dependency. So I would rather keep "they depend on the meilisearch-js", which is clearer I think.

2021-12-16 07:19 UTC, mdubus requested changes

2021-12-16 07:19 UTC, mdubus commented on resources/dependencies.md
> +- [`gatsby-plugin-meilsearch`](https://github.com/meilisearch/gatsby-plugin-meilisearch/)
```suggestion
- [`gatsby-plugin-meilisearch`](https://github.com/meilisearch/gatsby-plugin-meilisearch/)
```

2021-12-16 07:19 UTC, mdubus commented on resources/dependencies.md
> +- [`strapi-plugin-meilsearch`](https://github.com/meilisearch/strapi-plugin-meilisearch/)
```suggestion
- [`strapi-plugin-meilisearch`](https://github.com/meilisearch/strapi-plugin-meilisearch/)
```

2021-12-16 07:19 UTC, mdubus commented on resources/dependencies.md
> +- [`meiliseach-symfony`](https://github.com/meilisearch/meilisearch-symfony/)
```suggestion
- [`meilisearch-symfony`](https://github.com/meilisearch/meilisearch-symfony/)
```

2021-12-16 07:19 UTC, mdubus commented on resources/dependencies.md
> +- [`meiliseach-rails`](https://github.com/meilisearch/meilisearch-rails/)
```suggestion
- [`meilisearch-rails`](https://github.com/meilisearch/meilisearch-rails/)
```

2021-12-16 07:19 UTC, mdubus commented on resources/dependencies.md
> +- [`vuepress-plugin-meilsearch`](https://github.com/meilisearch/vuepress-plugin-meilisearch/)
```suggestion
- [`vuepress-plugin-meilisearch`](https://github.com/meilisearch/vuepress-plugin-meilisearch/)
```

2021-12-16 07:19 UTC, mdubus commented on resources/dependencies.md
> +- [`meiliseach-gcp`](https://github.com/meilisearch/meilisearch-gcp/)
```suggestion
- [`meilisearch-aws`](https://github.com/meilisearch/meilisearch-aws/)
- [`meilisearch-digitalocean`](https://github.com/meilisearch/meilisearch-gcp/)
- [`meilisearch-gcp`](https://github.com/meilisearch/meilisearch-gcp/)
```

2021-12-16 12:14 UTC, mdubus requested changes
Sorry I forgot this one on my first review 🙈

2021-12-16 12:14 UTC, mdubus commented on resources/dependencies.md
> +They depend on [`instant-meilsearch`](https://github.com/meilisearch/instant-meilisearch/)
```suggestion
They depend on [`instant-meilisearch`](https://github.com/meilisearch/instant-meilisearch/)
```

2021-12-16 12:33 UTC, bidoubiwa commented on resources/dependencies.md
> +They depend on [`meilisearch-js`](https://github.com/meilisearch/meilisearch-js):
Ah yes sorry completely wrong of me

2021-12-16 12:33 UTC, bidoubiwa commented on resources/dependencies.md
> +
Should I keep track of them myself meanwhile ?

2021-12-16 12:35 UTC, bidoubiwa submitted a review, later dismissed
LGTM 🔥

2021-12-16 16:38 UTC, curquiza commented on resources/dependencies.md
> +They depend on [`instant-meilsearch`](https://github.com/meilisearch/instant-meilisearch/)
```suggestion
They depend on [`instant-meilisearch`](https://github.com/meilisearch/instant-meilisearch/)
```

2021-12-16 16:39 UTC, curquiza commented on resources/dependencies.md
> +
Nope, not your job! This is the job of the devrel team to keep track of their own demos and be aware of their dependencies.

2021-12-16 16:41 UTC, merged

2021-12-16 16:54 UTC, bidoubiwa reviewed
LGTM 🔥🔥🔥